### ISSUE TITLE
Getting network ID

### ISSUE THREAD

**Issue by vojtechsimetka** [rsksmart/rif-marketplace-dev#5]
Create simple script to get the network ID for ganache and store it in the configs as well. This network ID is needed for RNS Admin.

This `curl` command can be used.
```
curl --location --request POST 'localhost:8545/' \
     --header 'Content-Type: application/json' \
     --data-raw '{
         "jsonrpc":"2.0",
         "method":"net_version",
         "params":[],
         "id":67
     }'
```

**Comment by julianmrodri** [comment]
I will close this issue as we dont need the Network ID as part of the setup anymore.
